FROM mcr.microsoft.com/vscode/devcontainers/python:3.11-bullseye
LABEL author="NCR"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Uninstall pre-installed formatting and linting tools
# They would conflict with our pinned versions
RUN \
    pipx uninstall black \
    && pipx uninstall pydocstyle \
    && pipx uninstall pycodestyle \
    && pipx uninstall mypy \
    && pipx uninstall pylint

ENV FILE_LOCATION "/usr/src/app"

# Disable host checking
RUN mkdir -p /root/.ssh && \
    echo "Host *" >> /root/.ssh/config && \
    echo "StrictHostKeyChecking no" >> /root/.ssh/config

# Folder to store JSON logs
RUN sudo mkdir -p /usr/logs

COPY . $FILE_LOCATION

WORKDIR $FILE_LOCATION/

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash