FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.11-bullseye
LABEL author="NCR"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ENV FILE_LOCATION "/usr/src/app"

# Disable host checking
RUN mkdir -p /root/.ssh && \
    echo "Host *" >> /root/.ssh/config && \
    echo "StrictHostKeyChecking no" >> /root/.ssh/config

# Folder to store JSON logs
RUN sudo mkdir -p /usr/logs

COPY . $FILE_LOCATION

WORKDIR $FILE_LOCATION/

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash