sources:
    # JPM China A (dist) USD
  - loader_class: pypmanager.loaders.shb_fonder.SHBFonderLoader
    isin_code: LU0051755006
    lookup_key: 0p000019da
    # Handelsbanken Sverige 100 Ind Cri A1 SEK
  - loader_class: pypmanager.loaders.shb_fonder.SHBFonderLoader
    isin_code: SE0003788587
    lookup_key: shb0000025
    # Avanza World Tech by TIN
  - loader_class: pypmanager.loaders.ft.FTLoader
    isin_code: SE0014453221
    lookup_key: 601933686
    # Handelsbanken Hållbar Energi
  - loader_class: pypmanager.loaders.ft.FTLoader
    isin_code: SE0005965662
    lookup_key: 535679922
    # Avanza Sverige
  - loader_class: pypmanager.loaders.ft.FTLoader
    isin_code: SE0014956850
    lookup_key: 679312906
    # Länsförsäkringar Global Index
  - loader_class: pypmanager.loaders.ft.FTLoader
    isin_code: SE0005188836
    lookup_key: 535619835
    # Länsförsäkringar Tillväxtmarknad Index A
  - loader_class: pypmanager.loaders.ft.FTLoader
    isin_code: SE0005796331
    lookup_key: 535627197
    # PLUS Fastigheter Sverige Index
  - loader_class: pypmanager.loaders.ft.FTLoader
    isin_code: SE0016798805
    lookup_key: 681984998
    # Storebrand Emerging Markets A SEK
  - loader_class: pypmanager.loaders.ft.FTLoader
    isin_code: SE0003455658
    lookup_key: 535686415
    # Storebrand Global Plus A SEK
  - loader_class: pypmanager.loaders.ft.FTLoader
    isin_code: SE0008129985
    lookup_key: 535691067
    # Storebrand Sverige A SEK
  - loader_class: pypmanager.loaders.ft.FTLoader
    isin_code: SE0000529992
    lookup_key: 535673247
